### ISSUE TITLE
What is the recommended way to destroy/cancel/reset GideonReplay instance?

### ISSUE THREAD

**Issue by arpitnarechania** [tmdt-buw/gideon-replay#3]
I have a Typescript component which gets loaded in multiple times.

Each time, I am re-initializing the instance via `this.gideonInstance = Gideon.getInstance();`; and it does work. However, when I fetch `this.gideonInstance.getHistoryRecords()`, I get a cumulative list of records, i.e., when I load gideonInstance for the *n*th time, the history from *n-1* loads is also returned. I just want the history from the *n*th load for which I need to somehow destroy the instance before re-initializing it.

Any pointers? Thank you!

**Comment by tfunken** [comment]
I am not quite sure if I have understood the problem correctly. Gideon currently follows the singleton pattern, i.e. `Gideon.getInstance()` will always return the same instance as long as the web page has not been completely reloaded (in which case the instance is recreated once). 

The gideon instance keeps an array of the entire history of all tracked elements, which in turn contain all interactions of the respective element. ` getHistoryRecords(): LocationHistory[]` returns an array of all interactions performed on all tracked elements. If you are only interested in the history of the latest element, you could just use a method to return the latest history element:

```
/**
   * Return last element in history
   */
getLatestHistoryElement(history: LocationHistory[]) {
  const len = history.length;
  if (len > 0) {
    return history[len - 1];
  }
  return null;
}
```

Otherwise, to completely reset the history you could try simply passing an empty array into the import function (i.e. `Gideon.getInstance().importHistory([])` . This should set the complete history to the empty array.

**Comment by arpitnarechania** [comment]
You got the question right. Thanks for the response; this is exactly what I was looking for.
